local_costmap:
   inflation_radius: 0.25
   global_frame: /odom
   robot_base_frame: /base_link
   update_frequency: 2.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 6.0
   height: 6.0
   resolution: 0.025
   transform_tolerance: 1.0
   map_type: costmap
   plugins:
     - {name: obstacle_layer,     type: "costmap_2d::ObstacleLayer"}
#    - {name: range_sensor_layer, type: "range_sensor_layer::RangeSensorLayer"}
#    - {name: inflation_layer,    type: "costmap_2d::InflationLayer"}
